const Questions = [
  {
    id: 1,
    question: "How do i guess  the right answer ?",
    answer:"In this game, the correct answer is unknown to both of us. However, it is important to note that the correct answer will always be a randomly generated number within the range of 1 to 5.",
  },

  {
    id: 2,
    question:
      "why is my balance deducting after clicking the 'place bet' button ?",
    answer:
      'Please note that when you enter an amount in the stake box, the corresponding value will be deducted from your balance once you click the "place bet" button.',
  },
  {
    id: 3,
    question: "Can i change the amount i want to bet?",
    answer:
      'yes you can, but this can be done before you click on the "place bet" button ',
  },

  {
    id: 4,
    question: "What is the meaning of random ?",
    answer:
      " a random number can be any number,but  In this game, the random number generated can be any number within the range of 1 to 5. Therefore, it's important to keep in mind that the correct answer will vary each time you place a bet.",
  },
  {
    id: 5,
    question: "How do i know if i win",
    answer:"To win in this game, you need to correctly guess the number that the computer generates after clicking the 'check number  button. If your guess matches the computer's number, you will be declared the winner and your balance would be updated immediately"
  },
  {
    id: 6,
    question: "can you explain this game ",
    answer:"Certainly! In this game, the first input prompt will ask you to enter the amount you want to stake. Once you input the desired amount, another prompt will appear, asking you to guess a number between 1 and 5. Please ensure that your guess falls within this range. If the number you guessed matches the number generated by the computer, you will win. However, if your guess does not match the computer's number, you will lose the bet.",
  },
  {
    id:7,
    question:'how does the winning works ',
    answer:"If the amount you stake is below $10, you will win twice (2x) the amount you bet. However, if the amount you stake is $10 or higher, you will win three times (3x) the amount you bet."
  }
];

export default Questions;
